sidebar:
    user_logs:
        title:  Logs
        icon:   fas fa-history
        submenu:
            log_session:     { title: Sessioni,  route: kikwik_admin_user_log_session }
            log_request:     { title: Dettagli,  route: kikwik_admin_user_log_request }
admins:
    user_log_session:
        entityClass: Kikwik\UserLogBundle\Entity\SessionLog
        controller: Kikwik\UserLogBundle\Controller\Admin\SessionLogController
        singularName: log sessione
        pluralName: log sessioni
        gender: female
        fields:
            user:             { label: Utente }
            userIdentifier:   { label: Utente }
            sessionId:        { label: Identificativo }
            remoteIp:         { label: IP utente }
            createdAt:        { label: Prima richiesta }
            updatedAt:        { label: Ultima richiesta }
            requestLogs:      { label: Richieste, displayType: collectionList }
            requestLogsCount: { label: Richieste }
            duration:         { label: Durata }
        collection:
            display: [ user, sessionId, remoteIp, createdAt, updatedAt, requestLogsCount, duration ]
            export: [ user, sessionId, remoteIp, createdAt, updatedAt, requestLogsCount, duration ]
            sort: [ updatedAt, desc ]
            filters: [ userIdentifier, createdAt, updatedAt ]
            actions:
                new:  { enabled: false }
        object:
            display: [ user, sessionId, remoteIp, createdAt, updatedAt, requestLogs, duration ]
            actions:
                show: { emodal: false }
                edit: { enabled: false }
                delete: { enabled: false }
    user_log_request:
        entityClass: Kikwik\UserLogBundle\Entity\RequestLog
        singularName: log richiesta
        pluralName: log richieste
        gender: female
        fields:
            sessionLog:                 { searchPath: sessionLog }
            sessionLogIdentifier:       { label: Sessione }
            sessionId:                  { label: Identificativo }
            action:                     { label: Controller }
            method:                     { label: Metodo }
            methodAndControllerHtml:    { label: Metodo, sortPath: method }
            responseStatusCode:         { label: Status code }
            responseStatusCodeHtml:     { label: Status code, sortPath: responseStatusCode }
            pathInfo:                   { label: Url }
            parameters:                 { label: Parametri }
            parametersHtml:             { label: Parametri, sortPath: parameters }
            createdAt:                  { label: Data richiesta }
        collection:
            display: [ createdAt, sessionLogIdentifier, methodAndControllerHtml, responseStatusCodeHtml, pathInfo, parametersHtml ]
            export: [ createdAt, sessionLogIdentifier, controller, method, responseStatusCode, responseStatusText, pathInfo, parameters ]
            filters: [ sessionLogIdentifier, method, responseStatusCode, pathInfo, parameters ]
            sort: [ createdAt, asc ]
            paginationSize: 100
            actions:
                new:  { enabled: false }
        object:
            actions:
                edit: { enabled: false }
                delete: { enabled: false }